// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/depin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuntimeType defines how the container should be executed
type RuntimeType int32

const (
	RuntimeType_RUNTIME_SCRIPT             RuntimeType = 0 // Inject script file, run with interpreter (default, backward compat)
	RuntimeType_RUNTIME_DOCKER_IMAGE       RuntimeType = 1 // Custom Docker image + command, no script injection
	RuntimeType_RUNTIME_PERSISTENT_SERVICE RuntimeType = 2 // Long-running container with health checks and port exposure
)

// Enum value maps for RuntimeType.
var (
	RuntimeType_name = map[int32]string{
		0: "RUNTIME_SCRIPT",
		1: "RUNTIME_DOCKER_IMAGE",
		2: "RUNTIME_PERSISTENT_SERVICE",
	}
	RuntimeType_value = map[string]int32{
		"RUNTIME_SCRIPT":             0,
		"RUNTIME_DOCKER_IMAGE":       1,
		"RUNTIME_PERSISTENT_SERVICE": 2,
	}
)

func (x RuntimeType) Enum() *RuntimeType {
	p := new(RuntimeType)
	*p = x
	return p
}

func (x RuntimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_depin_proto_enumTypes[0].Descriptor()
}

func (RuntimeType) Type() protoreflect.EnumType {
	return &file_proto_depin_proto_enumTypes[0]
}

func (x RuntimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeType.Descriptor instead.
func (RuntimeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{0}
}

// GPUInfo contains detailed specifications for a single GPU
type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // GPU model name (e.g. "NVIDIA GeForce RTX 4090")
	VramMb        int64                  `protobuf:"varint,2,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`                     // Video Memory in Megabytes
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"` // Driver version (e.g. "535.104")
	CudaVersion   string                 `protobuf:"bytes,4,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version,omitempty"`       // CUDA version (e.g. "12.2")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_proto_depin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{0}
}

func (x *GPUInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUInfo) GetVramMb() int64 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUInfo) GetCudaVersion() string {
	if x != nil {
		return x.CudaVersion
	}
	return ""
}

// ResourceLimits contains the maximum resource limits for containers on a node
type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxCpu        float64                `protobuf:"fixed64,1,opt,name=max_cpu,json=maxCpu,proto3" json:"max_cpu,omitempty"`                 // Max CPU cores (e.g., 2.0 for 2 cores)
	MaxRamGb      float64                `protobuf:"fixed64,2,opt,name=max_ram_gb,json=maxRamGb,proto3" json:"max_ram_gb,omitempty"`         // Max RAM in GB
	MaxVolumeGb   int64                  `protobuf:"varint,3,opt,name=max_volume_gb,json=maxVolumeGb,proto3" json:"max_volume_gb,omitempty"` // Max disk space in GB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_depin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceLimits) GetMaxCpu() float64 {
	if x != nil {
		return x.MaxCpu
	}
	return 0
}

func (x *ResourceLimits) GetMaxRamGb() float64 {
	if x != nil {
		return x.MaxRamGb
	}
	return 0
}

func (x *ResourceLimits) GetMaxVolumeGb() int64 {
	if x != nil {
		return x.MaxVolumeGb
	}
	return 0
}

// NodeInfo contains information about a GPU node/agent
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Unique identifier for the node
	GpuModel      string                 `protobuf:"bytes,2,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`                // GPU model name (e.g., "NVIDIA RTX 4090")
	VramTotal     uint64                 `protobuf:"varint,3,opt,name=vram_total,json=vramTotal,proto3" json:"vram_total,omitempty"`            // Total VRAM in bytes
	VramFree      uint64                 `protobuf:"varint,4,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`               // Available VRAM in bytes
	DockerVersion string                 `protobuf:"bytes,5,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"` // Docker version installed on the node
	// Hardware specs
	CpuModel      string     `protobuf:"bytes,7,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`              // CPU model (e.g. "Intel Core i9-13900K")
	CpuCores      int32      `protobuf:"varint,8,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`             // Physical cores
	RamTotalMb    int64      `protobuf:"varint,9,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`     // Total RAM in Megabytes
	DiskTotalGb   int64      `protobuf:"varint,10,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"` // Total Disk Space in GB
	OsInfo        string     `protobuf:"bytes,11,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`                   // OS Info (e.g. "Ubuntu 22.04 LTS")
	GpuInfo       []*GPUInfo `protobuf:"bytes,12,rep,name=gpu_info,json=gpuInfo,proto3" json:"gpu_info,omitempty"`                // List of GPUs in the node
	AgentVersion  string     `protobuf:"bytes,13,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"` // Agent software version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_depin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *NodeInfo) GetVramTotal() uint64 {
	if x != nil {
		return x.VramTotal
	}
	return 0
}

func (x *NodeInfo) GetVramFree() uint64 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

func (x *NodeInfo) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *NodeInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *NodeInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeInfo) GetRamTotalMb() int64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *NodeInfo) GetDiskTotalGb() int64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *NodeInfo) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *NodeInfo) GetGpuInfo() []*GPUInfo {
	if x != nil {
		return x.GpuInfo
	}
	return nil
}

func (x *NodeInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

// RegistrationResponse is returned after a node registration attempt
type RegistrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                                       // Status of the registration (e.g., "success", "error")
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                     // Human-readable message about the registration result
	ResourceLimits *ResourceLimits        `protobuf:"bytes,3,opt,name=resource_limits,json=resourceLimits,proto3" json:"resource_limits,omitempty"` // Initial resource limits for the node
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_proto_depin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegistrationResponse) GetResourceLimits() *ResourceLimits {
	if x != nil {
		return x.ResourceLimits
	}
	return nil
}

// JobFile represents a file to inject into the container workspace
type JobFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // Relative path inside /app (e.g., "model/network.py", "config.yaml")
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // File content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFile) Reset() {
	*x = JobFile{}
	mi := &file_proto_depin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFile) ProtoMessage() {}

func (x *JobFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFile.ProtoReflect.Descriptor instead.
func (*JobFile) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{4}
}

func (x *JobFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *JobFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// HealthCheck defines how to verify a persistent service is running correctly
type HealthCheck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Endpoint            string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                                     // HTTP path to check (e.g., "/health", "/ready")
	Port                int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                                                            // Port to check on the container
	IntervalSeconds     int32                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`               // Check interval (default: 30)
	TimeoutSeconds      int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                  // Per-check timeout (default: 5)
	Retries             int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`                                                      // Consecutive failures before marking unhealthy (default: 3)
	InitialDelaySeconds int32                  `protobuf:"varint,6,opt,name=initial_delay_seconds,json=initialDelaySeconds,proto3" json:"initial_delay_seconds,omitempty"` // Wait before first check (default: 10)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_proto_depin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheck) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HealthCheck) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HealthCheck) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *HealthCheck) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *HealthCheck) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

func (x *HealthCheck) GetInitialDelaySeconds() int32 {
	if x != nil {
		return x.InitialDelaySeconds
	}
	return 0
}

// PortMapping maps a container port to a host port for external access
type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"` // Port inside the container
	HostPort      int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`                // Port on the host (0 = auto-assign)
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`                                 // "tcp" or "udp" (default: "tcp")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_proto_depin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{6}
}

func (x *PortMapping) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// JobRequest is sent from orchestrator to agent to execute a container
type JobRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                      // Unique identifier for this job
	Image            string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                                   // Docker image to run (e.g., "python:3.11-slim", "node:20", "alpine")
	Command          []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`                                               // Command to execute (e.g., ["python", "train.py"] or ["node", "server.js"])
	ScriptContent    string                 `protobuf:"bytes,4,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`              // Script content to inject (used with RUNTIME_SCRIPT, injected as entrypoint file)
	MemoryLimitMb    int64                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`           // Memory limit in MB (e.g., 512 for 512MB)
	CpuLimit         float32                `protobuf:"fixed32,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`                           // CPU limit (e.g., 0.5 for half core, 1.0 for one core)
	TimeoutSeconds   int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`          // Execution timeout in seconds (0 = no timeout for services)
	Requirements     []string               `protobuf:"bytes,8,rep,name=requirements,proto3" json:"requirements,omitempty"`                                     // Package dependencies to install before execution (e.g., ["numpy", "express"])
	Files            []*JobFile             `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`                                                   // Additional files to inject into /app
	Entrypoint       string                 `protobuf:"bytes,10,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`                                        // Script filename to execute (default: "task.py" for SCRIPT mode)
	MaxArtifactBytes int64                  `protobuf:"varint,11,opt,name=max_artifact_bytes,json=maxArtifactBytes,proto3" json:"max_artifact_bytes,omitempty"` // Max artifact output size in bytes (0 = no artifact collection)
	// Phase 1: Universal compute fields
	RuntimeType    RuntimeType       `protobuf:"varint,12,opt,name=runtime_type,json=runtimeType,proto3,enum=depin.RuntimeType" json:"runtime_type,omitempty"`                                // Execution mode (default: RUNTIME_SCRIPT)
	Environment    map[string]string `protobuf:"bytes,13,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // User-defined environment variables
	PortMappings   []*PortMapping    `protobuf:"bytes,14,rep,name=port_mappings,json=portMappings,proto3" json:"port_mappings,omitempty"`                                                     // Ports to expose (for PERSISTENT_SERVICE)
	HealthCheck    *HealthCheck      `protobuf:"bytes,15,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`                                                        // Health check config (for PERSISTENT_SERVICE)
	GpuCount       int32             `protobuf:"varint,16,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`                                                                // GPUs requested (0 = CPU only, -1 = all available)
	ShmSizeMb      int64             `protobuf:"varint,17,opt,name=shm_size_mb,json=shmSizeMb,proto3" json:"shm_size_mb,omitempty"`                                                           // Override shared memory size (0 = auto-calculate)
	InstallCommand string            `protobuf:"bytes,18,opt,name=install_command,json=installCommand,proto3" json:"install_command,omitempty"`                                               // Custom dependency install command (e.g., "npm install", "pip install -r requirements.txt")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_depin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{7}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *JobRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *JobRequest) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *JobRequest) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *JobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobRequest) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *JobRequest) GetFiles() []*JobFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *JobRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *JobRequest) GetMaxArtifactBytes() int64 {
	if x != nil {
		return x.MaxArtifactBytes
	}
	return 0
}

func (x *JobRequest) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_RUNTIME_SCRIPT
}

func (x *JobRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *JobRequest) GetPortMappings() []*PortMapping {
	if x != nil {
		return x.PortMappings
	}
	return nil
}

func (x *JobRequest) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *JobRequest) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *JobRequest) GetShmSizeMb() int64 {
	if x != nil {
		return x.ShmSizeMb
	}
	return 0
}

func (x *JobRequest) GetInstallCommand() string {
	if x != nil {
		return x.InstallCommand
	}
	return ""
}

// Heartbeat contains real-time telemetry data for live graphs
type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                // Unique node identifier
	CpuPercent      float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`                  // Current CPU usage (0-100)
	RamPercent      float64                `protobuf:"fixed64,3,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`                  // Current RAM usage (0-100)
	Uptime          string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                                              // System uptime as human-readable string (e.g., "2h 15m 30s")
	GpuPercent      float64                `protobuf:"fixed64,5,opt,name=gpu_percent,json=gpuPercent,proto3" json:"gpu_percent,omitempty"`                  // Current GPU usage (0-100)
	VramPercent     float64                `protobuf:"fixed64,6,opt,name=vram_percent,json=vramPercent,proto3" json:"vram_percent,omitempty"`               // Current VRAM usage (0-100)
	VramTotal       uint64                 `protobuf:"varint,7,opt,name=vram_total,json=vramTotal,proto3" json:"vram_total,omitempty"`                      // Total VRAM in bytes
	VramFree        uint64                 `protobuf:"varint,8,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`                         // Available VRAM in bytes
	GpuModel        string                 `protobuf:"bytes,9,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`                          // GPU Model name
	Timestamp       string                 `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                       // Timestamp of the heartbeat
	SentTimestampMs int64                  `protobuf:"varint,11,opt,name=sent_timestamp_ms,json=sentTimestampMs,proto3" json:"sent_timestamp_ms,omitempty"` // Unix timestamp in milliseconds when heartbeat was sent (for RTT calculation)
	RunningJobs     []string               `protobuf:"bytes,12,rep,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`                // Job IDs currently executing on this node
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_depin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{8}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetRamPercent() float64 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *Heartbeat) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *Heartbeat) GetGpuPercent() float64 {
	if x != nil {
		return x.GpuPercent
	}
	return 0
}

func (x *Heartbeat) GetVramPercent() float64 {
	if x != nil {
		return x.VramPercent
	}
	return 0
}

func (x *Heartbeat) GetVramTotal() uint64 {
	if x != nil {
		return x.VramTotal
	}
	return 0
}

func (x *Heartbeat) GetVramFree() uint64 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

func (x *Heartbeat) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *Heartbeat) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Heartbeat) GetSentTimestampMs() int64 {
	if x != nil {
		return x.SentTimestampMs
	}
	return 0
}

func (x *Heartbeat) GetRunningJobs() []string {
	if x != nil {
		return x.RunningJobs
	}
	return nil
}

// JobStats contains execution statistics for completed jobs
type JobStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeakCpuPercent float64                `protobuf:"fixed64,1,opt,name=peak_cpu_percent,json=peakCpuPercent,proto3" json:"peak_cpu_percent,omitempty"` // Peak CPU usage during execution
	DurationMs     int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                // Total execution duration in milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStats) Reset() {
	*x = JobStats{}
	mi := &file_proto_depin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStats) ProtoMessage() {}

func (x *JobStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStats.ProtoReflect.Descriptor instead.
func (*JobStats) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{9}
}

func (x *JobStats) GetPeakCpuPercent() float64 {
	if x != nil {
		return x.PeakCpuPercent
	}
	return 0
}

func (x *JobStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// ArtifactInfo describes a file produced by the container in /app/output/
type ArtifactInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                     // Relative path (e.g., "model.pt", "results/metrics.csv")
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // File size
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // File content (for small artifacts, max ~50MB total)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactInfo) Reset() {
	*x = ArtifactInfo{}
	mi := &file_proto_depin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactInfo) ProtoMessage() {}

func (x *ArtifactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactInfo.ProtoReflect.Descriptor instead.
func (*ArtifactInfo) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactInfo) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// JobResult is sent from agent back to orchestrator with execution results
type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`             // Job ID this result belongs to
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // Status: "running", "completed", "failed"
	OutputLog     string                 `protobuf:"bytes,3,opt,name=output_log,json=outputLog,proto3" json:"output_log,omitempty"` // Container output/logs
	Stats         *JobStats              `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`                          // Execution statistics (optional, only on completion)
	Artifacts     []*ArtifactInfo        `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`                  // Output files from /app/output/
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_depin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{11}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResult) GetOutputLog() string {
	if x != nil {
		return x.OutputLog
	}
	return ""
}

func (x *JobResult) GetStats() *JobStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *JobResult) GetArtifacts() []*ArtifactInfo {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

// JobLog is sent from agent to orchestrator for real-time log streaming
type JobLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // Job ID this log belongs to
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`                // Single log line from container stdout/stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLog) Reset() {
	*x = JobLog{}
	mi := &file_proto_depin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLog) ProtoMessage() {}

func (x *JobLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLog.ProtoReflect.Descriptor instead.
func (*JobLog) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{12}
}

func (x *JobLog) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLog) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// ServiceStatus reports the state of a persistent service (agent -> orchestrator)
type ServiceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                                                                  // Job ID of the service
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                                                                             // "starting", "healthy", "unhealthy", "stopped"
	PortMap       map[string]int32       `protobuf:"bytes,3,rep,name=port_map,json=portMap,proto3" json:"port_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // container_port -> actual_host_port mapping
	HealthMessage string                 `protobuf:"bytes,4,opt,name=health_message,json=healthMessage,proto3" json:"health_message,omitempty"`                                                          // Human-readable status detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_proto_depin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ServiceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceStatus) GetPortMap() map[string]int32 {
	if x != nil {
		return x.PortMap
	}
	return nil
}

func (x *ServiceStatus) GetHealthMessage() string {
	if x != nil {
		return x.HealthMessage
	}
	return ""
}

// ResourceLimitsUpdate is sent from orchestrator to agent when limits change
type ResourceLimitsUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limits        *ResourceLimits        `protobuf:"bytes,1,opt,name=limits,proto3" json:"limits,omitempty"`                        // New resource limits
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimitsUpdate) Reset() {
	*x = ResourceLimitsUpdate{}
	mi := &file_proto_depin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimitsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimitsUpdate) ProtoMessage() {}

func (x *ResourceLimitsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimitsUpdate.ProtoReflect.Descriptor instead.
func (*ResourceLimitsUpdate) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{14}
}

func (x *ResourceLimitsUpdate) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ResourceLimitsUpdate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// HeartbeatAck is sent from orchestrator to agent as acknowledgment of heartbeat
type HeartbeatAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ReceivedTimestampMs int64                  `protobuf:"varint,1,opt,name=received_timestamp_ms,json=receivedTimestampMs,proto3" json:"received_timestamp_ms,omitempty"` // Orchestrator timestamp when heartbeat was received
	SentTimestampMs     int64                  `protobuf:"varint,2,opt,name=sent_timestamp_ms,json=sentTimestampMs,proto3" json:"sent_timestamp_ms,omitempty"`             // Echo of agent's sent_timestamp_ms for RTT calculation
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_depin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatAck) GetReceivedTimestampMs() int64 {
	if x != nil {
		return x.ReceivedTimestampMs
	}
	return 0
}

func (x *HeartbeatAck) GetSentTimestampMs() int64 {
	if x != nil {
		return x.SentTimestampMs
	}
	return 0
}

// StopService is sent from orchestrator to agent to stop a persistent service
type StopService struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                           // Job ID of the service to stop
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"` // Time to wait before force kill (default: 30)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopService) Reset() {
	*x = StopService{}
	mi := &file_proto_depin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopService) ProtoMessage() {}

func (x *StopService) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopService.ProtoReflect.Descriptor instead.
func (*StopService) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{16}
}

func (x *StopService) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StopService) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// ServerEvent wraps messages sent from orchestrator to agent
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_JobRequest
	//	*ServerEvent_ResourceLimitsUpdate
	//	*ServerEvent_HeartbeatAck
	//	*ServerEvent_StopService
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_depin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{17}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetJobRequest() *JobRequest {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_JobRequest); ok {
			return x.JobRequest
		}
	}
	return nil
}

func (x *ServerEvent) GetResourceLimitsUpdate() *ResourceLimitsUpdate {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ResourceLimitsUpdate); ok {
			return x.ResourceLimitsUpdate
		}
	}
	return nil
}

func (x *ServerEvent) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerEvent) GetStopService() *StopService {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_StopService); ok {
			return x.StopService
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_JobRequest struct {
	JobRequest *JobRequest `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3,oneof"`
}

type ServerEvent_ResourceLimitsUpdate struct {
	ResourceLimitsUpdate *ResourceLimitsUpdate `protobuf:"bytes,2,opt,name=resource_limits_update,json=resourceLimitsUpdate,proto3,oneof"`
}

type ServerEvent_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,3,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerEvent_StopService struct {
	StopService *StopService `protobuf:"bytes,4,opt,name=stop_service,json=stopService,proto3,oneof"`
}

func (*ServerEvent_JobRequest) isServerEvent_Event() {}

func (*ServerEvent_ResourceLimitsUpdate) isServerEvent_Event() {}

func (*ServerEvent_HeartbeatAck) isServerEvent_Event() {}

func (*ServerEvent_StopService) isServerEvent_Event() {}

// AgentEvent wraps messages sent from agent to orchestrator
type AgentEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Identifies which agent is sending this event
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_JobResult
	//	*AgentEvent_JobLog
	//	*AgentEvent_ServiceStatus
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_proto_depin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{18}
}

func (x *AgentEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentEvent) GetJobLog() *JobLog {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_JobLog); ok {
			return x.JobLog
		}
	}
	return nil
}

func (x *AgentEvent) GetServiceStatus() *ServiceStatus {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_ServiceStatus); ok {
			return x.ServiceStatus
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // Real-time telemetry (every 3s)
}

type AgentEvent_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,3,opt,name=job_result,json=jobResult,proto3,oneof"` // Result of a job execution
}

type AgentEvent_JobLog struct {
	JobLog *JobLog `protobuf:"bytes,4,opt,name=job_log,json=jobLog,proto3,oneof"` // Real-time log line from job execution
}

type AgentEvent_ServiceStatus struct {
	ServiceStatus *ServiceStatus `protobuf:"bytes,5,opt,name=service_status,json=serviceStatus,proto3,oneof"` // Persistent service health/state update
}

func (*AgentEvent_Heartbeat) isAgentEvent_Event() {}

func (*AgentEvent_JobResult) isAgentEvent_Event() {}

func (*AgentEvent_JobLog) isAgentEvent_Event() {}

func (*AgentEvent_ServiceStatus) isAgentEvent_Event() {}

var File_proto_depin_proto protoreflect.FileDescriptor

const file_proto_depin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/depin.proto\x12\x05depin\"\x80\x01\n" +
	"\aGPUInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\avram_mb\x18\x02 \x01(\x03R\x06vramMb\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\x12!\n" +
	"\fcuda_version\x18\x04 \x01(\tR\vcudaVersion\"k\n" +
	"\x0eResourceLimits\x12\x17\n" +
	"\amax_cpu\x18\x01 \x01(\x01R\x06maxCpu\x12\x1c\n" +
	"\n" +
	"max_ram_gb\x18\x02 \x01(\x01R\bmaxRamGb\x12\"\n" +
	"\rmax_volume_gb\x18\x03 \x01(\x03R\vmaxVolumeGb\"\x83\x03\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tgpu_model\x18\x02 \x01(\tR\bgpuModel\x12\x1d\n" +
	"\n" +
	"vram_total\x18\x03 \x01(\x04R\tvramTotal\x12\x1b\n" +
	"\tvram_free\x18\x04 \x01(\x04R\bvramFree\x12%\n" +
	"\x0edocker_version\x18\x05 \x01(\tR\rdockerVersion\x12\x1b\n" +
	"\tcpu_model\x18\a \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\b \x01(\x05R\bcpuCores\x12 \n" +
	"\fram_total_mb\x18\t \x01(\x03R\n" +
	"ramTotalMb\x12\"\n" +
	"\rdisk_total_gb\x18\n" +
	" \x01(\x03R\vdiskTotalGb\x12\x17\n" +
	"\aos_info\x18\v \x01(\tR\x06osInfo\x12)\n" +
	"\bgpu_info\x18\f \x03(\v2\x0e.depin.GPUInfoR\agpuInfo\x12#\n" +
	"\ragent_version\x18\r \x01(\tR\fagentVersion\"\x88\x01\n" +
	"\x14RegistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x0fresource_limits\x18\x03 \x01(\v2\x15.depin.ResourceLimitsR\x0eresourceLimits\"7\n" +
	"\aJobFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xdf\x01\n" +
	"\vHealthCheck\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x05R\x0fintervalSeconds\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretries\x122\n" +
	"\x15initial_delay_seconds\x18\x06 \x01(\x05R\x13initialDelaySeconds\"m\n" +
	"\vPortMapping\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x93\x06\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12%\n" +
	"\x0escript_content\x18\x04 \x01(\tR\rscriptContent\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x03R\rmemoryLimitMb\x12\x1b\n" +
	"\tcpu_limit\x18\x06 \x01(\x02R\bcpuLimit\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12\"\n" +
	"\frequirements\x18\b \x03(\tR\frequirements\x12$\n" +
	"\x05files\x18\t \x03(\v2\x0e.depin.JobFileR\x05files\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\n" +
	" \x01(\tR\n" +
	"entrypoint\x12,\n" +
	"\x12max_artifact_bytes\x18\v \x01(\x03R\x10maxArtifactBytes\x125\n" +
	"\fruntime_type\x18\f \x01(\x0e2\x12.depin.RuntimeTypeR\vruntimeType\x12D\n" +
	"\venvironment\x18\r \x03(\v2\".depin.JobRequest.EnvironmentEntryR\venvironment\x127\n" +
	"\rport_mappings\x18\x0e \x03(\v2\x12.depin.PortMappingR\fportMappings\x125\n" +
	"\fhealth_check\x18\x0f \x01(\v2\x12.depin.HealthCheckR\vhealthCheck\x12\x1b\n" +
	"\tgpu_count\x18\x10 \x01(\x05R\bgpuCount\x12\x1e\n" +
	"\vshm_size_mb\x18\x11 \x01(\x03R\tshmSizeMb\x12'\n" +
	"\x0finstall_command\x18\x12 \x01(\tR\x0einstallCommand\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x03\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x03 \x01(\x01R\n" +
	"ramPercent\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\x12\x1f\n" +
	"\vgpu_percent\x18\x05 \x01(\x01R\n" +
	"gpuPercent\x12!\n" +
	"\fvram_percent\x18\x06 \x01(\x01R\vvramPercent\x12\x1d\n" +
	"\n" +
	"vram_total\x18\a \x01(\x04R\tvramTotal\x12\x1b\n" +
	"\tvram_free\x18\b \x01(\x04R\bvramFree\x12\x1b\n" +
	"\tgpu_model\x18\t \x01(\tR\bgpuModel\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\tR\ttimestamp\x12*\n" +
	"\x11sent_timestamp_ms\x18\v \x01(\x03R\x0fsentTimestampMs\x12!\n" +
	"\frunning_jobs\x18\f \x03(\tR\vrunningJobs\"U\n" +
	"\bJobStats\x12(\n" +
	"\x10peak_cpu_percent\x18\x01 \x01(\x01R\x0epeakCpuPercent\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\"c\n" +
	"\fArtifactInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"\xb3\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"output_log\x18\x03 \x01(\tR\toutputLog\x12%\n" +
	"\x05stats\x18\x04 \x01(\v2\x0f.depin.JobStatsR\x05stats\x121\n" +
	"\tartifacts\x18\x05 \x03(\v2\x13.depin.ArtifactInfoR\tartifacts\"3\n" +
	"\x06JobLog\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"\xdf\x01\n" +
	"\rServiceStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12<\n" +
	"\bport_map\x18\x03 \x03(\v2!.depin.ServiceStatus.PortMapEntryR\aportMap\x12%\n" +
	"\x0ehealth_message\x18\x04 \x01(\tR\rhealthMessage\x1a:\n" +
	"\fPortMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"d\n" +
	"\x14ResourceLimitsUpdate\x12-\n" +
	"\x06limits\x18\x01 \x01(\v2\x15.depin.ResourceLimitsR\x06limits\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\"n\n" +
	"\fHeartbeatAck\x122\n" +
	"\x15received_timestamp_ms\x18\x01 \x01(\x03R\x13receivedTimestampMs\x12*\n" +
	"\x11sent_timestamp_ms\x18\x02 \x01(\x03R\x0fsentTimestampMs\"V\n" +
	"\vStopService\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\"\x96\x02\n" +
	"\vServerEvent\x124\n" +
	"\vjob_request\x18\x01 \x01(\v2\x11.depin.JobRequestH\x00R\n" +
	"jobRequest\x12S\n" +
	"\x16resource_limits_update\x18\x02 \x01(\v2\x1b.depin.ResourceLimitsUpdateH\x00R\x14resourceLimitsUpdate\x12:\n" +
	"\rheartbeat_ack\x18\x03 \x01(\v2\x13.depin.HeartbeatAckH\x00R\fheartbeatAck\x127\n" +
	"\fstop_service\x18\x04 \x01(\v2\x12.depin.StopServiceH\x00R\vstopServiceB\a\n" +
	"\x05event\"\xfc\x01\n" +
	"\n" +
	"AgentEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.depin.HeartbeatH\x00R\theartbeat\x121\n" +
	"\n" +
	"job_result\x18\x03 \x01(\v2\x10.depin.JobResultH\x00R\tjobResult\x12(\n" +
	"\ajob_log\x18\x04 \x01(\v2\r.depin.JobLogH\x00R\x06jobLog\x12=\n" +
	"\x0eservice_status\x18\x05 \x01(\v2\x14.depin.ServiceStatusH\x00R\rserviceStatusB\a\n" +
	"\x05event*[\n" +
	"\vRuntimeType\x12\x12\n" +
	"\x0eRUNTIME_SCRIPT\x10\x00\x12\x18\n" +
	"\x14RUNTIME_DOCKER_IMAGE\x10\x01\x12\x1e\n" +
	"\x1aRUNTIME_PERSISTENT_SERVICE\x10\x022\x86\x01\n" +
	"\vNodeService\x12:\n" +
	"\bRegister\x12\x0f.depin.NodeInfo\x1a\x1b.depin.RegistrationResponse\"\x00\x12;\n" +
	"\fStreamEvents\x12\x11.depin.AgentEvent\x1a\x12.depin.ServerEvent\"\x00(\x010\x01B,Z*github.com/oHakan/depin-orchestrator/protob\x06proto3"

var (
	file_proto_depin_proto_rawDescOnce sync.Once
	file_proto_depin_proto_rawDescData []byte
)

func file_proto_depin_proto_rawDescGZIP() []byte {
	file_proto_depin_proto_rawDescOnce.Do(func() {
		file_proto_depin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_depin_proto_rawDesc), len(file_proto_depin_proto_rawDesc)))
	})
	return file_proto_depin_proto_rawDescData
}

var file_proto_depin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_depin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_depin_proto_goTypes = []any{
	(RuntimeType)(0),             // 0: depin.RuntimeType
	(*GPUInfo)(nil),              // 1: depin.GPUInfo
	(*ResourceLimits)(nil),       // 2: depin.ResourceLimits
	(*NodeInfo)(nil),             // 3: depin.NodeInfo
	(*RegistrationResponse)(nil), // 4: depin.RegistrationResponse
	(*JobFile)(nil),              // 5: depin.JobFile
	(*HealthCheck)(nil),          // 6: depin.HealthCheck
	(*PortMapping)(nil),          // 7: depin.PortMapping
	(*JobRequest)(nil),           // 8: depin.JobRequest
	(*Heartbeat)(nil),            // 9: depin.Heartbeat
	(*JobStats)(nil),             // 10: depin.JobStats
	(*ArtifactInfo)(nil),         // 11: depin.ArtifactInfo
	(*JobResult)(nil),            // 12: depin.JobResult
	(*JobLog)(nil),               // 13: depin.JobLog
	(*ServiceStatus)(nil),        // 14: depin.ServiceStatus
	(*ResourceLimitsUpdate)(nil), // 15: depin.ResourceLimitsUpdate
	(*HeartbeatAck)(nil),         // 16: depin.HeartbeatAck
	(*StopService)(nil),          // 17: depin.StopService
	(*ServerEvent)(nil),          // 18: depin.ServerEvent
	(*AgentEvent)(nil),           // 19: depin.AgentEvent
	nil,                          // 20: depin.JobRequest.EnvironmentEntry
	nil,                          // 21: depin.ServiceStatus.PortMapEntry
}
var file_proto_depin_proto_depIdxs = []int32{
	1,  // 0: depin.NodeInfo.gpu_info:type_name -> depin.GPUInfo
	2,  // 1: depin.RegistrationResponse.resource_limits:type_name -> depin.ResourceLimits
	5,  // 2: depin.JobRequest.files:type_name -> depin.JobFile
	0,  // 3: depin.JobRequest.runtime_type:type_name -> depin.RuntimeType
	20, // 4: depin.JobRequest.environment:type_name -> depin.JobRequest.EnvironmentEntry
	7,  // 5: depin.JobRequest.port_mappings:type_name -> depin.PortMapping
	6,  // 6: depin.JobRequest.health_check:type_name -> depin.HealthCheck
	10, // 7: depin.JobResult.stats:type_name -> depin.JobStats
	11, // 8: depin.JobResult.artifacts:type_name -> depin.ArtifactInfo
	21, // 9: depin.ServiceStatus.port_map:type_name -> depin.ServiceStatus.PortMapEntry
	2,  // 10: depin.ResourceLimitsUpdate.limits:type_name -> depin.ResourceLimits
	8,  // 11: depin.ServerEvent.job_request:type_name -> depin.JobRequest
	15, // 12: depin.ServerEvent.resource_limits_update:type_name -> depin.ResourceLimitsUpdate
	16, // 13: depin.ServerEvent.heartbeat_ack:type_name -> depin.HeartbeatAck
	17, // 14: depin.ServerEvent.stop_service:type_name -> depin.StopService
	9,  // 15: depin.AgentEvent.heartbeat:type_name -> depin.Heartbeat
	12, // 16: depin.AgentEvent.job_result:type_name -> depin.JobResult
	13, // 17: depin.AgentEvent.job_log:type_name -> depin.JobLog
	14, // 18: depin.AgentEvent.service_status:type_name -> depin.ServiceStatus
	3,  // 19: depin.NodeService.Register:input_type -> depin.NodeInfo
	19, // 20: depin.NodeService.StreamEvents:input_type -> depin.AgentEvent
	4,  // 21: depin.NodeService.Register:output_type -> depin.RegistrationResponse
	18, // 22: depin.NodeService.StreamEvents:output_type -> depin.ServerEvent
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_depin_proto_init() }
func file_proto_depin_proto_init() {
	if File_proto_depin_proto != nil {
		return
	}
	file_proto_depin_proto_msgTypes[17].OneofWrappers = []any{
		(*ServerEvent_JobRequest)(nil),
		(*ServerEvent_ResourceLimitsUpdate)(nil),
		(*ServerEvent_HeartbeatAck)(nil),
		(*ServerEvent_StopService)(nil),
	}
	file_proto_depin_proto_msgTypes[18].OneofWrappers = []any{
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_JobResult)(nil),
		(*AgentEvent_JobLog)(nil),
		(*AgentEvent_ServiceStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_depin_proto_rawDesc), len(file_proto_depin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_depin_proto_goTypes,
		DependencyIndexes: file_proto_depin_proto_depIdxs,
		EnumInfos:         file_proto_depin_proto_enumTypes,
		MessageInfos:      file_proto_depin_proto_msgTypes,
	}.Build()
	File_proto_depin_proto = out.File
	file_proto_depin_proto_goTypes = nil
	file_proto_depin_proto_depIdxs = nil
}
