// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/depin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GPUInfo contains detailed specifications for a single GPU
type GPUInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                        // GPU model name (e.g. "NVIDIA GeForce RTX 4090")
	VramMb        int64                  `protobuf:"varint,2,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`                     // Video Memory in Megabytes
	DriverVersion string                 `protobuf:"bytes,3,opt,name=driver_version,json=driverVersion,proto3" json:"driver_version,omitempty"` // Driver version (e.g. "535.104")
	CudaVersion   string                 `protobuf:"bytes,4,opt,name=cuda_version,json=cudaVersion,proto3" json:"cuda_version,omitempty"`       // CUDA version (e.g. "12.2")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInfo) Reset() {
	*x = GPUInfo{}
	mi := &file_proto_depin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInfo) ProtoMessage() {}

func (x *GPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInfo.ProtoReflect.Descriptor instead.
func (*GPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{0}
}

func (x *GPUInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUInfo) GetVramMb() int64 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

func (x *GPUInfo) GetDriverVersion() string {
	if x != nil {
		return x.DriverVersion
	}
	return ""
}

func (x *GPUInfo) GetCudaVersion() string {
	if x != nil {
		return x.CudaVersion
	}
	return ""
}

// NodeInfo contains information about a GPU node/agent
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Unique identifier for the node
	GpuModel      string                 `protobuf:"bytes,2,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`                // GPU model name (e.g., "NVIDIA RTX 4090")
	VramTotal     uint64                 `protobuf:"varint,3,opt,name=vram_total,json=vramTotal,proto3" json:"vram_total,omitempty"`            // Total VRAM in bytes
	VramFree      uint64                 `protobuf:"varint,4,opt,name=vram_free,json=vramFree,proto3" json:"vram_free,omitempty"`               // Available VRAM in bytes
	DockerVersion string                 `protobuf:"bytes,5,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"` // Docker version installed on the node
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`                   // Clerk User ID of the node provider
	// New hardware specs
	CpuModel      string     `protobuf:"bytes,7,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`              // CPU model (e.g. "Intel Core i9-13900K")
	CpuCores      int32      `protobuf:"varint,8,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`             // Physical cores
	RamTotalMb    int64      `protobuf:"varint,9,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`     // Total RAM in Megabytes
	DiskTotalGb   int64      `protobuf:"varint,10,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"` // Total Disk Space in GB
	OsInfo        string     `protobuf:"bytes,11,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`                   // OS Info (e.g. "Ubuntu 22.04 LTS")
	GpuInfo       []*GPUInfo `protobuf:"bytes,12,rep,name=gpu_info,json=gpuInfo,proto3" json:"gpu_info,omitempty"`                // List of GPUs in the node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_depin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *NodeInfo) GetVramTotal() uint64 {
	if x != nil {
		return x.VramTotal
	}
	return 0
}

func (x *NodeInfo) GetVramFree() uint64 {
	if x != nil {
		return x.VramFree
	}
	return 0
}

func (x *NodeInfo) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *NodeInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *NodeInfo) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *NodeInfo) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeInfo) GetRamTotalMb() int64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *NodeInfo) GetDiskTotalGb() int64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *NodeInfo) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *NodeInfo) GetGpuInfo() []*GPUInfo {
	if x != nil {
		return x.GpuInfo
	}
	return nil
}

// RegistrationResponse is returned after a node registration attempt
type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // Status of the registration (e.g., "success", "error")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Human-readable message about the registration result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_proto_depin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{2}
}

func (x *RegistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// JobRequest is sent from orchestrator to agent to execute a container
type JobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                             // Unique identifier for this job
	Image          string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`                                          // Docker image to run (e.g., "alpine")
	Command        []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`                                      // Command to execute in the container
	ScriptContent  string                 `protobuf:"bytes,4,opt,name=script_content,json=scriptContent,proto3" json:"script_content,omitempty"`     // Raw Python script content to execute
	MemoryLimitMb  int64                  `protobuf:"varint,5,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`  // Memory limit in MB (e.g., 512 for 512MB)
	CpuLimit       float32                `protobuf:"fixed32,6,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`                  // CPU limit (e.g., 0.5 for half core, 1.0 for one core)
	TimeoutSeconds int32                  `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Execution timeout in seconds (e.g., 60)
	Requirements   []string               `protobuf:"bytes,8,rep,name=requirements,proto3" json:"requirements,omitempty"`                            // Python dependencies to install (e.g., ["numpy", "pandas"])
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_depin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{3}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JobRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *JobRequest) GetScriptContent() string {
	if x != nil {
		return x.ScriptContent
	}
	return ""
}

func (x *JobRequest) GetMemoryLimitMb() int64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *JobRequest) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *JobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *JobRequest) GetRequirements() []string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

// Heartbeat contains real-time telemetry data for live graphs
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`               // Unique node identifier
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // Current CPU usage (0-100)
	RamPercent    float64                `protobuf:"fixed64,3,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"` // Current RAM usage (0-100)
	Uptime        string                 `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`                             // System uptime as human-readable string (e.g., "2h 15m 30s")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_depin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetRamPercent() float64 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *Heartbeat) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

// JobStats contains execution statistics for completed jobs
type JobStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PeakCpuPercent float64                `protobuf:"fixed64,1,opt,name=peak_cpu_percent,json=peakCpuPercent,proto3" json:"peak_cpu_percent,omitempty"` // Peak CPU usage during execution
	DurationMs     int64                  `protobuf:"varint,2,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`                // Total execution duration in milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobStats) Reset() {
	*x = JobStats{}
	mi := &file_proto_depin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStats) ProtoMessage() {}

func (x *JobStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStats.ProtoReflect.Descriptor instead.
func (*JobStats) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{5}
}

func (x *JobStats) GetPeakCpuPercent() float64 {
	if x != nil {
		return x.PeakCpuPercent
	}
	return 0
}

func (x *JobStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// JobResult is sent from agent back to orchestrator with execution results
type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`             // Job ID this result belongs to
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // Status: "running", "completed", "failed"
	OutputLog     string                 `protobuf:"bytes,3,opt,name=output_log,json=outputLog,proto3" json:"output_log,omitempty"` // Container output/logs
	Stats         *JobStats              `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`                          // Execution statistics (optional, only on completion)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_depin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{6}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResult) GetOutputLog() string {
	if x != nil {
		return x.OutputLog
	}
	return ""
}

func (x *JobResult) GetStats() *JobStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// JobLog is sent from agent to orchestrator for real-time log streaming
type JobLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // Job ID this log belongs to
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`                // Single log line from container stdout/stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLog) Reset() {
	*x = JobLog{}
	mi := &file_proto_depin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLog) ProtoMessage() {}

func (x *JobLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLog.ProtoReflect.Descriptor instead.
func (*JobLog) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{7}
}

func (x *JobLog) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLog) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// ServerEvent wraps messages sent from orchestrator to agent
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_JobRequest
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_proto_depin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{8}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetJobRequest() *JobRequest {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_JobRequest); ok {
			return x.JobRequest
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_JobRequest struct {
	JobRequest *JobRequest `protobuf:"bytes,1,opt,name=job_request,json=jobRequest,proto3,oneof"`
}

func (*ServerEvent_JobRequest) isServerEvent_Event() {}

// AgentEvent wraps messages sent from agent to orchestrator
type AgentEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Identifies which agent is sending this event
	// Types that are valid to be assigned to Event:
	//
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_JobResult
	//	*AgentEvent_JobLog
	Event         isAgentEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_proto_depin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_depin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_proto_depin_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentEvent) GetEvent() isAgentEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *AgentEvent) GetJobLog() *JobLog {
	if x != nil {
		if x, ok := x.Event.(*AgentEvent_JobLog); ok {
			return x.JobLog
		}
	}
	return nil
}

type isAgentEvent_Event interface {
	isAgentEvent_Event()
}

type AgentEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // Real-time telemetry (every 3s)
}

type AgentEvent_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,3,opt,name=job_result,json=jobResult,proto3,oneof"` // Result of a job execution
}

type AgentEvent_JobLog struct {
	JobLog *JobLog `protobuf:"bytes,4,opt,name=job_log,json=jobLog,proto3,oneof"` // Real-time log line from job execution
}

func (*AgentEvent_Heartbeat) isAgentEvent_Event() {}

func (*AgentEvent_JobResult) isAgentEvent_Event() {}

func (*AgentEvent_JobLog) isAgentEvent_Event() {}

var File_proto_depin_proto protoreflect.FileDescriptor

const file_proto_depin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/depin.proto\x12\x05depin\"\x80\x01\n" +
	"\aGPUInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\avram_mb\x18\x02 \x01(\x03R\x06vramMb\x12%\n" +
	"\x0edriver_version\x18\x03 \x01(\tR\rdriverVersion\x12!\n" +
	"\fcuda_version\x18\x04 \x01(\tR\vcudaVersion\"\xf9\x02\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tgpu_model\x18\x02 \x01(\tR\bgpuModel\x12\x1d\n" +
	"\n" +
	"vram_total\x18\x03 \x01(\x04R\tvramTotal\x12\x1b\n" +
	"\tvram_free\x18\x04 \x01(\x04R\bvramFree\x12%\n" +
	"\x0edocker_version\x18\x05 \x01(\tR\rdockerVersion\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x1b\n" +
	"\tcpu_model\x18\a \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\b \x01(\x05R\bcpuCores\x12 \n" +
	"\fram_total_mb\x18\t \x01(\x03R\n" +
	"ramTotalMb\x12\"\n" +
	"\rdisk_total_gb\x18\n" +
	" \x01(\x03R\vdiskTotalGb\x12\x17\n" +
	"\aos_info\x18\v \x01(\tR\x06osInfo\x12)\n" +
	"\bgpu_info\x18\f \x03(\v2\x0e.depin.GPUInfoR\agpuInfo\"H\n" +
	"\x14RegistrationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8c\x02\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12%\n" +
	"\x0escript_content\x18\x04 \x01(\tR\rscriptContent\x12&\n" +
	"\x0fmemory_limit_mb\x18\x05 \x01(\x03R\rmemoryLimitMb\x12\x1b\n" +
	"\tcpu_limit\x18\x06 \x01(\x02R\bcpuLimit\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12\"\n" +
	"\frequirements\x18\b \x03(\tR\frequirements\"~\n" +
	"\tHeartbeat\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x03 \x01(\x01R\n" +
	"ramPercent\x12\x16\n" +
	"\x06uptime\x18\x04 \x01(\tR\x06uptime\"U\n" +
	"\bJobStats\x12(\n" +
	"\x10peak_cpu_percent\x18\x01 \x01(\x01R\x0epeakCpuPercent\x12\x1f\n" +
	"\vduration_ms\x18\x02 \x01(\x03R\n" +
	"durationMs\"\x80\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"output_log\x18\x03 \x01(\tR\toutputLog\x12%\n" +
	"\x05stats\x18\x04 \x01(\v2\x0f.depin.JobStatsR\x05stats\"3\n" +
	"\x06JobLog\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"L\n" +
	"\vServerEvent\x124\n" +
	"\vjob_request\x18\x01 \x01(\v2\x11.depin.JobRequestH\x00R\n" +
	"jobRequestB\a\n" +
	"\x05event\"\xbd\x01\n" +
	"\n" +
	"AgentEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.depin.HeartbeatH\x00R\theartbeat\x121\n" +
	"\n" +
	"job_result\x18\x03 \x01(\v2\x10.depin.JobResultH\x00R\tjobResult\x12(\n" +
	"\ajob_log\x18\x04 \x01(\v2\r.depin.JobLogH\x00R\x06jobLogB\a\n" +
	"\x05event2\x86\x01\n" +
	"\vNodeService\x12:\n" +
	"\bRegister\x12\x0f.depin.NodeInfo\x1a\x1b.depin.RegistrationResponse\"\x00\x12;\n" +
	"\fStreamEvents\x12\x11.depin.AgentEvent\x1a\x12.depin.ServerEvent\"\x00(\x010\x01B,Z*github.com/oHakan/depin-orchestrator/protob\x06proto3"

var (
	file_proto_depin_proto_rawDescOnce sync.Once
	file_proto_depin_proto_rawDescData []byte
)

func file_proto_depin_proto_rawDescGZIP() []byte {
	file_proto_depin_proto_rawDescOnce.Do(func() {
		file_proto_depin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_depin_proto_rawDesc), len(file_proto_depin_proto_rawDesc)))
	})
	return file_proto_depin_proto_rawDescData
}

var file_proto_depin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_depin_proto_goTypes = []any{
	(*GPUInfo)(nil),              // 0: depin.GPUInfo
	(*NodeInfo)(nil),             // 1: depin.NodeInfo
	(*RegistrationResponse)(nil), // 2: depin.RegistrationResponse
	(*JobRequest)(nil),           // 3: depin.JobRequest
	(*Heartbeat)(nil),            // 4: depin.Heartbeat
	(*JobStats)(nil),             // 5: depin.JobStats
	(*JobResult)(nil),            // 6: depin.JobResult
	(*JobLog)(nil),               // 7: depin.JobLog
	(*ServerEvent)(nil),          // 8: depin.ServerEvent
	(*AgentEvent)(nil),           // 9: depin.AgentEvent
}
var file_proto_depin_proto_depIdxs = []int32{
	0, // 0: depin.NodeInfo.gpu_info:type_name -> depin.GPUInfo
	5, // 1: depin.JobResult.stats:type_name -> depin.JobStats
	3, // 2: depin.ServerEvent.job_request:type_name -> depin.JobRequest
	4, // 3: depin.AgentEvent.heartbeat:type_name -> depin.Heartbeat
	6, // 4: depin.AgentEvent.job_result:type_name -> depin.JobResult
	7, // 5: depin.AgentEvent.job_log:type_name -> depin.JobLog
	1, // 6: depin.NodeService.Register:input_type -> depin.NodeInfo
	9, // 7: depin.NodeService.StreamEvents:input_type -> depin.AgentEvent
	2, // 8: depin.NodeService.Register:output_type -> depin.RegistrationResponse
	8, // 9: depin.NodeService.StreamEvents:output_type -> depin.ServerEvent
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_depin_proto_init() }
func file_proto_depin_proto_init() {
	if File_proto_depin_proto != nil {
		return
	}
	file_proto_depin_proto_msgTypes[8].OneofWrappers = []any{
		(*ServerEvent_JobRequest)(nil),
	}
	file_proto_depin_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_JobResult)(nil),
		(*AgentEvent_JobLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_depin_proto_rawDesc), len(file_proto_depin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_depin_proto_goTypes,
		DependencyIndexes: file_proto_depin_proto_depIdxs,
		MessageInfos:      file_proto_depin_proto_msgTypes,
	}.Build()
	File_proto_depin_proto = out.File
	file_proto_depin_proto_goTypes = nil
	file_proto_depin_proto_depIdxs = nil
}
